//! Writing Rust for a [`Vocabulary`].
//!
//! The output is plain Rust calling the hand-written helpers in
//! `ojak_vocab::json`. It is formatted by `rustfmt` afterwards, so this
//! module only has to get the tokens right, not the layout.

use crate::model::{Hook, Literal, Property, Range, Type, Vocabulary};
use anyhow::{Context, Result, bail};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::io::Write as _;
use std::process::{Command, Stdio};

/// The actor types, which a range names together often enough to deserve a
/// name of its own.
const ACTORS: [&str; 5] = ["Application", "Group", "Organization", "Person", "Service"];

/// Generate the formatted Rust source for `vocabulary`.
///
/// # Errors
///
/// When `rustfmt` cannot be run or rejects the output, which would be a bug
/// here.
pub fn render(vocabulary: &Vocabulary) -> Result<String> {
    rustfmt(&generate(vocabulary)?)
}

/// Generate unformatted Rust source for `vocabulary`.
///
/// # Errors
///
/// When a property's ranges cannot be represented.
pub fn generate(vocabulary: &Vocabulary) -> Result<String> {
    let mut enums: BTreeMap<String, EnumDef> = BTreeMap::new();
    let mut out = String::new();
    out.push_str(HEADER);

    let mut types: Vec<&Type> = vocabulary.types.values().collect();
    types.sort_by(|a, b| a.name.cmp(&b.name));
    let untyped = untyped_types(vocabulary);
    let mut serde_names: Vec<String> = Vec::new();
    for t in &types {
        emit_struct(
            &mut out,
            vocabulary,
            t,
            untyped.contains(&t.uri),
            &mut enums,
        )?;
        serde_names.push(t.name.clone());
    }
    for (name, def) in &enums {
        emit_enum(&mut out, vocabulary, name, def);
        serde_names.push(name.clone());
    }
    let _ = writeln!(out, "serde_via_json!({});", serde_names.join(", "));
    Ok(out)
}

const HEADER: &str = r"//! Vocabulary types generated from Fedify's schemas.
//!
//! Do not edit this file. It is written by `cargo run -p ojak-vocab-gen`
//! from *crates/ojak-vocab/schemas*, which are Fedify's work under the MIT
//! license in that directory, and a test fails when it differs from what the
//! generator would write now.
//!
//! Each type reads a document in the form [`crate::read`] produces and writes
//! one in the same spelling. A property that may take several types takes an
//! enum of them, with `Iri` for a reference and `Other` for anything no
//! schema describes.

use alloc::{boxed::Box, string::String, vec::Vec};
use serde_json::Value;

use crate::{
    Iri, Reference,
    json::{self, FromJson, JsonError, ProofPurpose, Text, ToJson, Units, serde_via_json},
};

";

/// A generated enum: the variants a range allows.
#[derive(Clone, Debug, Default)]
struct EnumDef {
    /// Type IRIs, by the variant name they get.
    types: BTreeMap<String, String>,
    literals: BTreeSet<Literal>,
    /// Whether a bare IRI is a value: a reference to an entity, or an IRI
    /// literal.
    iri: bool,
    /// The ranges as the schema wrote them, for the enum's documentation.
    declared: Vec<Range>,
}

/// What Rust type a property's values take, and how to read and write them.
struct FieldCode {
    ty: String,
    read: String,
    write: String,
}

/// The types some property sends without a `type`, and which therefore need
/// reading and writing without one. A typeless type needs nothing extra.
fn untyped_types(vocabulary: &Vocabulary) -> BTreeSet<String> {
    vocabulary
        .types
        .values()
        .flat_map(|t| &t.properties)
        .filter(|property| property.untyped)
        .filter_map(|property| match property.ranges.as_slice() {
            [Range::Type(uri)] if vocabulary.types[uri].type_term.is_some() => Some(uri.clone()),
            _ => None,
        })
        .collect()
}

fn emit_struct(
    out: &mut String,
    vocabulary: &Vocabulary,
    t: &Type,
    sent_untyped: bool,
    enums: &mut BTreeMap<String, EnumDef>,
) -> Result<()> {
    doc(out, "", &first_paragraph(&t.description));
    let _ = writeln!(out, "///\n/// The type `{}`.", t.uri);
    let _ = writeln!(out, "#[derive(Clone, Debug, Default, PartialEq)]");
    let _ = writeln!(out, "pub struct {} {{", t.name);
    if t.entity {
        let _ = writeln!(out, "    /// The IRI that identifies this object.");
        let _ = writeln!(out, "    pub id: Option<Iri>,");
    }
    let mut fields = Vec::new();
    for property in &t.properties {
        let code = field_code(vocabulary, property, enums)
            .with_context(|| format!("{}.{}", t.name, property.field))?;
        if property.declared_by == t.name {
            doc(out, "    ", &first_paragraph(&property.description));
        } else {
            let _ = writeln!(
                out,
                "    /// See [`{}::{}`].",
                property.declared_by, property.field
            );
        }
        let _ = writeln!(out, "    pub {}: {},", property.field, code.ty);
        fields.push((property, code));
    }
    let _ = writeln!(out, "}}\n");

    let _ = writeln!(out, "impl {} {{", t.name);
    if sent_untyped {
        let _ = writeln!(
            out,
            "    /// Read a `{}` sent without its `type`, as some properties send it.",
            t.name
        );
        let _ = writeln!(
            out,
            "    ///\n    /// # Errors\n    ///\n    /// When `value` is not an object."
        );
        let _ = writeln!(
            out,
            "    pub fn from_json_untyped(value: &Value) -> Result<Self, JsonError> {{"
        );
        let _ = writeln!(out, "        let object = json::object(value)?;");
        let _ = writeln!(out, "        Ok(Self {{");
        if t.entity {
            let _ = writeln!(out, "            id: json::id(object),");
        }
        for (property, code) in &fields {
            let _ = writeln!(out, "            {}: {},", property.field, code.read);
        }
        let _ = writeln!(
            out,
            "        }})
    }}
"
        );
        let _ = writeln!(
            out,
            "    /// Write a `{}` without its `type`, as some properties send it.",
            t.name
        );
        let _ = writeln!(out, "    #[must_use]");
        let _ = writeln!(out, "    pub fn to_json_untyped(&self) -> Value {{");
        let _ = writeln!(
            out,
            "        json::without_type(self.to_json())
    }}
"
        );
    }
    let _ = writeln!(out, "    /// The type's IRI.");
    let _ = writeln!(out, "    pub const TYPE_IRI: &'static str = {:?};", t.uri);
    if let Some(term) = &t.type_term {
        let _ = writeln!(out, "    /// The type's `type` in a normalised document.");
        let _ = writeln!(out, "    pub const TYPE: &'static str = {term:?};");
    }
    let _ = writeln!(out, "}}\n");
    if let Some(term) = &t.type_term {
        let _ = writeln!(
            out,
            "impl json::Typed for {} {{\n    const TYPE: &'static str = {term:?};\n}}\n",
            t.name
        );
    }

    let _ = writeln!(out, "impl FromJson for {} {{", t.name);
    let _ = writeln!(
        out,
        "    fn from_json(value: &Value) -> Result<Self, JsonError> {{"
    );
    let _ = writeln!(out, "        let object = json::object(value)?;");
    if t.type_term.is_some() {
        let _ = writeln!(out, "        json::expect_type(object, Self::TYPE)?;");
    }
    let _ = writeln!(out, "        Ok(Self {{");
    if t.entity {
        let _ = writeln!(out, "            id: json::id(object),");
    }
    for (property, code) in &fields {
        let _ = writeln!(out, "            {}: {},", property.field, code.read);
    }
    let _ = writeln!(out, "        }})\n    }}\n}}\n");

    let _ = writeln!(out, "impl ToJson for {} {{", t.name);
    let _ = writeln!(out, "    fn to_json(&self) -> Value {{");
    let type_term = if t.type_term.is_some() {
        "Some(Self::TYPE)"
    } else {
        "None"
    };
    let id = if t.entity { "self.id.as_ref()" } else { "None" };
    let binding = if fields.is_empty() { "" } else { "mut " };
    let _ = writeln!(
        out,
        "        let {binding}object = json::new_object({type_term}, {id});"
    );
    for (_, code) in &fields {
        let _ = writeln!(out, "        {};", code.write);
    }
    let _ = writeln!(out, "        Value::Object(object)\n    }}\n}}\n");
    Ok(())
}

fn field_code(
    vocabulary: &Vocabulary,
    property: &Property,
    enums: &mut BTreeMap<String, EnumDef>,
) -> Result<FieldCode> {
    let field = &property.field;
    let text_only = property
        .ranges
        .contains(&Range::Literal(Literal::LangString))
        && property
            .ranges
            .iter()
            .all(|range| matches!(range, Range::Literal(Literal::LangString | Literal::String)));
    if property.untyped
        && let [Range::Type(uri)] = property.ranges.as_slice()
        && let Some(name) = vocabulary.types[uri]
            .type_term
            .as_ref()
            .map(|_| &vocabulary.types[uri].name)
    {
        return Ok(untyped_field_code(
            property,
            name,
            vocabulary.types[uri].entity,
        ));
    }
    if text_only {
        ensure_no_redundancy(property)?;
        return Ok(FieldCode {
            ty: "Text".into(),
            read: format!("json::text(object, {:?})", property.key),
            write: format!(
                "json::put_text(&mut object, {:?}, &self.{field})",
                property.key
            ),
        });
    }
    if property
        .ranges
        .contains(&Range::Literal(Literal::LangString))
    {
        bail!("text mixed with other ranges");
    }

    let value_type = value_type(vocabulary, property, enums)?;
    let keys = keys(property);
    let write_keys = write_keys(property);
    let reader = match (property.hook, property.functional) {
        (Some(Hook::LinkToImage), true) => {
            format!("json::one_mapped(object, {keys}, json::link_to_image)")
        }
        (Some(Hook::LinkToImage), false) => {
            format!("json::many_mapped(object, {keys}, json::link_to_image)")
        }
        (None, true) => format!("json::one(object, {keys})"),
        (None, false) => format!("json::many(object, {keys})"),
    };
    Ok(if property.functional {
        FieldCode {
            ty: format!("Option<{value_type}>"),
            read: reader,
            write: format!("json::put_one(&mut object, {write_keys}, self.{field}.as_ref())"),
        }
    } else {
        let element = value_type
            .strip_prefix("Box<")
            .and_then(|rest| rest.strip_suffix('>'))
            .map_or(value_type.clone(), str::to_owned);
        FieldCode {
            ty: format!("Vec<{element}>"),
            read: reader,
            write: format!("json::put_many(&mut object, {write_keys}, &self.{field})"),
        }
    })
}

/// A property whose single range type is sent without its `type`.
fn untyped_field_code(property: &Property, name: &str, entity: bool) -> FieldCode {
    let field = &property.field;
    let keys = keys(property);
    let write_keys = write_keys(property);
    let (element, read, write) = if entity {
        (
            format!("Reference<{name}>"),
            format!("|value| json::reference_with(value, {name}::from_json_untyped)"),
            format!("|reference| json::write_reference(reference, {name}::to_json_untyped)"),
        )
    } else if property.functional {
        (
            format!("Box<{name}>"),
            format!("|value| {name}::from_json_untyped(value).map(Box::new)"),
            "|value| value.to_json_untyped()".to_owned(),
        )
    } else {
        (
            name.to_owned(),
            format!("{name}::from_json_untyped"),
            format!("{name}::to_json_untyped"),
        )
    };
    if property.functional {
        FieldCode {
            ty: format!("Option<{element}>"),
            read: format!("json::one_with(object, {keys}, {read})"),
            write: format!(
                "json::put_one_with(&mut object, {write_keys}, self.{field}.as_ref(), {write})"
            ),
        }
    } else {
        FieldCode {
            ty: format!("Vec<{element}>"),
            read: format!("json::many_with(object, {keys}, {read})"),
            write: format!(
                "json::put_many_with(&mut object, {write_keys}, &self.{field}, {write})"
            ),
        }
    }
}

fn ensure_no_redundancy(property: &Property) -> Result<()> {
    if property.redundant_keys.is_empty() {
        Ok(())
    } else {
        bail!("text with redundant properties")
    }
}

/// The keys a property is read from, in order.
fn keys(property: &Property) -> String {
    let mut keys = vec![format!("{:?}", property.key)];
    keys.extend(property.redundant_keys.iter().map(|key| format!("{key:?}")));
    keys.extend(property.fallback_keys.iter().map(|key| format!("{key:?}")));
    format!("&[{}]", keys.join(", "))
}

/// The keys a property is written to: its own and its redundant ones.
fn write_keys(property: &Property) -> String {
    let mut keys = vec![format!("{:?}", property.key)];
    keys.extend(property.redundant_keys.iter().map(|key| format!("{key:?}")));
    format!("&[{}]", keys.join(", "))
}

/// The Rust type of one value of `property`.
fn value_type(
    vocabulary: &Vocabulary,
    property: &Property,
    enums: &mut BTreeMap<String, EnumDef>,
) -> Result<String> {
    if let [range] = property.ranges.as_slice() {
        match range {
            Range::Literal(literal) => return Ok(literal_type(*literal).to_owned()),
            Range::Type(uri) if vocabulary.descendants(uri).is_empty() => {
                let t = &vocabulary.types[uri];
                return Ok(if t.entity {
                    format!("Reference<{}>", t.name)
                } else {
                    format!("Box<{}>", t.name)
                });
            }
            Range::Type(_) => {}
        }
    }
    let name = enum_name(vocabulary, &property.ranges);
    let def = enums.entry(name.clone()).or_default();
    if def.declared.is_empty() {
        def.declared.clone_from(&property.ranges);
        for range in &property.ranges {
            match range {
                Range::Literal(literal) if literal.is_iri() => def.iri = true,
                Range::Literal(literal) => {
                    def.literals.insert(*literal);
                }
                Range::Type(uri) => {
                    let mut closure = vec![&vocabulary.types[uri]];
                    closure.extend(vocabulary.descendants(uri));
                    for t in closure {
                        if t.entity {
                            def.iri = true;
                        }
                        def.types.insert(t.name.clone(), t.uri.clone());
                    }
                }
            }
        }
    }
    Ok(name)
}

fn literal_type(literal: Literal) -> &'static str {
    match literal {
        Literal::Boolean => "bool",
        Literal::NonNegativeInteger => "u64",
        Literal::Float => "f64",
        Literal::Iri | Literal::TypeIri => "Iri",
        Literal::ProofPurpose => "ProofPurpose",
        Literal::Units => "Units",
        Literal::String
        | Literal::LangString
        | Literal::Decimal
        | Literal::DateTime
        | Literal::Duration
        | Literal::LanguageTag
        | Literal::PublicKeyPem
        | Literal::MultibaseKey
        | Literal::Multibase
        | Literal::Cryptosuite => "String",
    }
}

fn literal_name(literal: Literal) -> &'static str {
    match literal {
        Literal::String => "String",
        Literal::LangString => "Text",
        Literal::Boolean => "Boolean",
        Literal::NonNegativeInteger => "Integer",
        Literal::Float => "Float",
        Literal::Decimal => "Decimal",
        Literal::DateTime => "DateTime",
        Literal::Duration => "Duration",
        Literal::Iri | Literal::TypeIri => "Iri",
        Literal::LanguageTag => "LanguageTag",
        Literal::PublicKeyPem => "PublicKeyPem",
        Literal::MultibaseKey => "MultibaseKey",
        Literal::Multibase => "Multibase",
        Literal::Cryptosuite => "Cryptosuite",
        Literal::ProofPurpose => "ProofPurpose",
        Literal::Units => "Units",
    }
}

fn enum_name(vocabulary: &Vocabulary, ranges: &[Range]) -> String {
    let types: Vec<&str> = ranges
        .iter()
        .filter_map(|range| match range {
            Range::Type(uri) => Some(vocabulary.types[uri].name.as_str()),
            Range::Literal(_) => None,
        })
        .collect();
    let literals: Vec<&str> = ranges
        .iter()
        .filter_map(|range| match range {
            Range::Literal(literal) => Some(literal_name(*literal)),
            Range::Type(_) => None,
        })
        .collect();
    let mut sorted_types = types.clone();
    sorted_types.sort_unstable();
    if literals.is_empty() && sorted_types == ACTORS {
        return "AnyActor".to_owned();
    }
    if literals.is_empty()
        && let [only] = types.as_slice()
    {
        return format!("Any{only}");
    }
    let mut parts: Vec<&str> = sorted_types;
    parts.extend(literals);
    parts.join("Or")
}

fn emit_enum(out: &mut String, vocabulary: &Vocabulary, name: &str, def: &EnumDef) {
    let declared: Vec<String> = def
        .declared
        .iter()
        .map(|range| match range {
            Range::Type(uri) => format!("[`{}`]", vocabulary.types[uri].name),
            Range::Literal(literal) => format!("`{}`", literal_name(*literal)),
        })
        .collect();
    let _ = writeln!(
        out,
        "/// A value of {}, or of a type extending one of them.",
        declared.join(", ")
    );
    let _ = writeln!(out, "#[derive(Clone, Debug, PartialEq)]");
    let _ = writeln!(out, "pub enum {name} {{");
    if def.iri {
        let _ = writeln!(out, "    /// A reference, by IRI.");
        let _ = writeln!(out, "    Iri(Iri),");
    }
    for literal in &def.literals {
        let _ = writeln!(
            out,
            "    {}({}),",
            literal_name(*literal),
            literal_type(*literal)
        );
    }
    for variant in def.types.keys() {
        let _ = writeln!(out, "    {variant}(Box<{variant}>),");
    }
    let _ = writeln!(out, "    /// Anything no schema describes, as it was.");
    let _ = writeln!(out, "    Other(Value),");
    let _ = writeln!(out, "}}\n");

    if def.iri {
        let _ = writeln!(out, "impl {name} {{");
        let _ = writeln!(
            out,
            "    /// The IRI of the value: the reference itself, or the object's `id`."
        );
        let _ = writeln!(out, "    #[must_use]");
        let _ = writeln!(out, "    pub fn id(&self) -> Option<&Iri> {{");
        let _ = writeln!(out, "        match self {{");
        let _ = writeln!(out, "            Self::Iri(iri) => Some(iri),");
        for (variant, uri) in &def.types {
            if vocabulary.types[uri].entity {
                let _ = writeln!(
                    out,
                    "            Self::{variant}(object) => object.id.as_ref(),"
                );
            }
        }
        let _ = writeln!(out, "            _ => None,\n        }}\n    }}\n}}\n");
    }

    // Reading never fails: a value the enum has no variant for is kept.
    let _ = writeln!(out, "impl FromJson for {name} {{");
    let _ = writeln!(
        out,
        "    fn from_json(value: &Value) -> Result<Self, JsonError> {{"
    );
    let _ = writeln!(out, "        Ok(match value {{");
    // Strings: named literals first, then an IRI, then free text.
    let mut string_arms: Vec<String> = Vec::new();
    for literal in &def.literals {
        if matches!(literal, Literal::Units | Literal::ProofPurpose) {
            string_arms.push(format!(
                "if let Ok(v) = {}::from_json(value) {{ return Ok(Self::{}(v)); }}",
                literal_type(*literal),
                literal_name(*literal)
            ));
        }
    }
    if def.iri {
        string_arms
            .push("if let Ok(v) = Iri::from_json(value) { return Ok(Self::Iri(v)); }".into());
    }
    // Free text, if the range has any, takes whatever string is left.
    let fallback = def
        .literals
        .iter()
        .find(|literal| literal_type(**literal) == "String")
        .map_or_else(
            || "Self::Other(value.clone())".to_owned(),
            |literal| {
                format!(
                    "String::from_json(value).map_or_else(|_| Self::Other(value.clone()), Self::{})",
                    literal_name(*literal)
                )
            },
        );
    let _ = writeln!(
        out,
        "            Value::String(_) => {{ {} {fallback} }}",
        string_arms.join(" ")
    );
    for (literal, json_kind) in [
        (Literal::Boolean, "Bool"),
        (Literal::NonNegativeInteger, "Number"),
        (Literal::Float, "Number"),
    ] {
        if def.literals.contains(&literal) {
            let _ = writeln!(
                out,
                "            Value::{json_kind}(_) => {}::from_json(value).map_or_else(|_| Self::Other(value.clone()), Self::{}),",
                literal_type(literal),
                literal_name(literal)
            );
        }
    }
    let typeless: Vec<&String> = def
        .types
        .iter()
        .filter(|(_, uri)| vocabulary.types[*uri].type_term.is_none())
        .map(|(variant, _)| variant)
        .collect();
    let inspects_object = def.iri || !def.types.is_empty();
    let binding = if inspects_object { "object" } else { "_" };
    let _ = writeln!(out, "            Value::Object({binding}) => {{");
    if def.iri {
        let _ = writeln!(
            out,
            "                if object.len() == 1 && object.contains_key(\"id\") && let Ok(v) = Iri::from_json(value) {{ return Ok(Self::Iri(v)); }}"
        );
    }
    for (variant, uri) in &def.types {
        let t = &vocabulary.types[uri];
        if t.type_term.is_some() {
            let _ = writeln!(
                out,
                "                if json::has_type(object, {variant}::TYPE) {{ return Ok({variant}::from_json(value).map_or_else(|_| Self::Other(value.clone()), |v| Self::{variant}(Box::new(v)))); }}"
            );
        }
    }
    if let [variant] = typeless.as_slice() {
        let _ = writeln!(
            out,
            "                if !object.contains_key(\"type\") && let Ok(v) = {variant}::from_json(value) {{ return Ok(Self::{variant}(Box::new(v))); }}"
        );
    }
    let _ = writeln!(out, "                Self::Other(value.clone())");
    let _ = writeln!(out, "            }}");
    let _ = writeln!(out, "            _ => Self::Other(value.clone()),");
    let _ = writeln!(out, "        }})\n    }}\n}}\n");

    let _ = writeln!(out, "impl ToJson for {name} {{");
    let _ = writeln!(out, "    fn to_json(&self) -> Value {{");
    let _ = writeln!(out, "        match self {{");
    if def.iri {
        let _ = writeln!(out, "            Self::Iri(v) => v.to_json(),");
    }
    for literal in &def.literals {
        let _ = writeln!(
            out,
            "            Self::{}(v) => v.to_json(),",
            literal_name(*literal)
        );
    }
    for variant in def.types.keys() {
        let _ = writeln!(out, "            Self::{variant}(v) => v.to_json(),");
    }
    let _ = writeln!(out, "            Self::Other(v) => v.clone(),");
    let _ = writeln!(out, "        }}\n    }}\n}}\n");
}

/// The first paragraph of a schema description, with its reference-style
/// links made inline: their definitions are further down, and a link whose
/// definition is left behind is a broken link to rustdoc.
fn first_paragraph(description: &str) -> String {
    let paragraph = description
        .trim()
        .split("\n\n")
        .next()
        .unwrap_or("")
        .lines()
        .map(str::trim)
        .collect::<Vec<_>>()
        .join("\n");
    inline_references(&paragraph, description)
}

/// `[text][label]` and `[label]` as `[text](url)`, from `[label]: url` in
/// `description`. Without a definition, a full reference is its text and a
/// shortcut is escaped, so that rustdoc does not read it as a path.
fn inline_references(text: &str, description: &str) -> String {
    let definition = |label: &str| {
        description.lines().find_map(|line| {
            let rest = line.trim().strip_prefix('[')?;
            let (name, url) = rest.split_once("]:")?;
            (name == label).then(|| url.trim().to_owned())
        })
    };
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(open) = rest.find('[') {
        out.push_str(&rest[..open]);
        let after = &rest[open + 1..];
        let Some(close) = after
            .find(']')
            .filter(|close| !after[..*close].contains('['))
        else {
            out.push('[');
            rest = after;
            continue;
        };
        let link_text = &after[..close];
        let tail = &after[close + 1..];
        if tail.starts_with('(') {
            // Already inline.
            out.push('[');
            out.push_str(link_text);
            out.push(']');
            rest = tail;
        } else if let Some(label) = tail
            .strip_prefix('[')
            .and_then(|label| label.find(']').map(|end| &label[..end]))
        {
            match definition(label) {
                Some(url) => {
                    let _ = write!(out, "[{link_text}]({url})");
                }
                None => out.push_str(link_text),
            }
            rest = &tail[label.len() + 2..];
        } else {
            match definition(link_text) {
                Some(url) => {
                    let _ = write!(out, "[{link_text}]({url})");
                }
                None => {
                    let _ = write!(out, "\\[{link_text}\\]");
                }
            }
            rest = tail;
        }
    }
    out.push_str(rest);
    out
}

fn doc(out: &mut String, indent: &str, text: &str) {
    for line in text.lines() {
        if line.is_empty() {
            let _ = writeln!(out, "{indent}///");
        } else {
            let _ = writeln!(out, "{indent}/// {line}");
        }
    }
}

fn rustfmt(source: &str) -> Result<String> {
    let mut child = Command::new("rustfmt")
        .args(["--edition", "2024", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .context("run rustfmt")?;
    child
        .stdin
        .take()
        .context("rustfmt stdin")?
        .write_all(source.as_bytes())?;
    let output = child.wait_with_output()?;
    if !output.status.success() {
        bail!(
            "rustfmt rejected the generated code:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    String::from_utf8(output.stdout).context("rustfmt output")
}
