[package]
name = "ojak-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
sha2.workspace = true
rsa.workspace = true
chrono.workspace = true
url.workspace = true
reqwest.workspace = true
serde_json.workspace = true
ed25519-dalek.workspace = true
ml-dsa = "0.1"
rand_core = { version = "0.6", features = ["getrandom"] }
serde_jcs.workspace = true
bs58.workspace = true

[dev-dependencies]
rand = "0.8"

[lints]
workspace = true
